### ISSUE TITLE
UpdateHub didn't start properly

### ISSUE THREAD

**Issue by HolgerAusB** [NexovaDev/UpdateHub#1860]
### Description of issue:

Since about two weeks (maybe longer) UpdateHub is not starting properly after a reboot. It's icon is missing in the task bar, but there are four processes in the task manager. I need to kill these to start UpdateHub manually.

Same problem when starting it with parameter `--silent` on a prompt. which is the same parameter as in the autostart entry in HKCU\Software\Microsoft\Windows\CurrentVersion\Run

Starting UpdateHub without parameter works well. But I don't want to get UpdateHub in foreground when booting windows. Any hints where I can look into?

I am also using:
- HiBit StartUp Manager, since months in combination with UpdateHub without problems before about two weeks ago
- 'controlled folder access' in Windows Defender is activated and UpdateHub is allowed to write protected resources.

While I am writing this issue and testing around, I just saw the same error, which is filed here about 1000 times:

> Getting the error ```Error: Timeout reached
>     at C:\Users\Hagri\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:1201871```.

But that Timeout occurred only once, couldn't reproduce that by forcing 'check updates'. 

Thanks to all contributors for this great software. 

```
App version: 2.4.0
WinGet version: 1.8.1791
Device ID: 68236a7e-3660-407c-8f36-e20b04cb4256
OS version: 22631.3810  Windows 11 Pro 23H2
Electron version: 29.0.1
Node version: 20.9.0
Chrome version: 122.0.6261.57
```

**Comment by KK-Designs** [comment]
Just looked at this, something is error'ing UpdateHub out before it's able to complete its startup cycle. It's timing out because of that error, it's odd that the icon doesn't appear even after. Can you send the app's log file?

**Comment by HolgerAusB** [comment]
I feel like a bloody beginner right now, but I couldn't find the logfile. Where is it, please? Found no hints in Readme or FAQ, yet.

I now can reproduce timeout, it only occurs on 'windows update', but not on 'apps', but that might only be a side effect. Main problem is that UpdateHub is stuck while loading with `--silent`

And another point, I just saw. 'winget upgrade' usually shows up an app which I do not want to upgrade because of breaking changes. But now the upgrade list is empty, no results with `winget upgrade`. The app is still available with winget in a newer version, I checked that with `winget search`. So maybe there is a problem with winget?

In UpdateHub I had this app marked to ignore but now I see, that the ignore list is empty. It was not the only app on the ignore list. I put some apps on the list which failing to upgrade or failing to show their proper installed version number.

Hm, and counter is at 99 updated apps. I am not sure, but that feels too much to me, for just a few month of using, but might possible.

**Comment by HolgerAusB** [comment]
Any news on this, @KK-Designs? 

I tried to delay the start of UpdateHub by 10 minutes after booting with Startup-Manager. Since then, Updatehub only hangs about every fifth time. But I think the result is rather random. I rather suspect that it is due to the daily form of the Microsoft servers, which answer something unexpected. Or perhaps it is also trying to reach a server that is filtered out here by PiHole (wild guess).

**Comment by HolgerAusB** [comment]
As I now use a different software for updating my software, I close this issue. Thank you for your help.
