### ISSUE TITLE
program keeps loading + window title bar missing + button not working

### ISSUE THREAD

**Issue by sk666** [NexovaDev/UpdateHub#308]
Hi,

I'm new with this software and I use the 2.2.3 version. I have no windows title bar when I run update hub (the section of the window when we can close, minimize, enlarge window. I have this issue only on the updatehub software, other software or windows are fines.

Also, the software list keep loading even after 4h of updating software list.

Finally, the last problem that I see is I am not able to click on the "about" button in the settings and "report an issue", they are clickable but nothing happen when I click on theses buttons. To be able to quit the application, I need to quit it in the notification area of the task bar.

Please let me know if you need more information. See the attached screenshot for the title bar missing. I tried to uninstall it, reinstall it (with admin rights and without it), same problems appeared in both case.

Sorry for my english, it's not my native language.

Thank you
![01](https://github.com/KK-Designs/UpdateHub/assets/29050341/06e14d25-316b-4eb8-ab6c-17ff30856509)
![02](https://github.com/KK-Designs/UpdateHub/assets/29050341/ecc95fb9-5d55-4883-9946-d366c6142ea9)

**Comment by KK-Designs** [comment]
Open command prompt and type "winget" to see if it is installed. WinGet is a key dependency that our app relies on to get app information

**Comment by sk666** [comment]
thank you, there was a problem with winget, I fixed it. Everything seem to be working fine now except for the same CLI error than others for missing app and the -infin% in the dashboard:
![03](https://github.com/KK-Designs/UpdateHub/assets/29050341/49cdcc05-715b-49de-b41c-6472cf4b1c3b)

**Comment by KK-Designs** [comment]
Better error handling for the original error is fixed in the latest release [(v2.3.0)](https://github.com/NexovaDev/UpdateHub/releases/tag/v2.3.0). Closing as completed

**Comment by KK-Designs** [comment]
> thank you, there was a problem with winget, I fixed it. Everything seem to be working fine now except for the same CLI error than others for missing app and the -infin% in the dashboard: ![03](https://user-images.githubusercontent.com/29050341/274262994-49cdcc05-715b-49de-b41c-6472cf4b1c3b.PNG)

I think this happens if WinGet is outdated, go to the the settings page and send me a screenshot of the bottom part

**Comment by sk666** [comment]
@KK-Designs 

there is my screenshot:

![info version](https://github.com/NexovaDev/UpdateHub/assets/29050341/f471665b-155a-43a7-9b45-5f392c9c12fa)

**Comment by KK-Designs** [comment]
If this is about the -Infin% bug, I'll try to debug it more. I'll keep you updated here when I fix this
