### ISSUE TITLE
```Error: Timeout reached``` after uninstalling the last outdated apps

### ISSUE THREAD

**Issue by sauceSojaaa** [NexovaDev/UpdateHub#346]
Getting the error ```Error: Timeout reached
    at C:\Users\[user]\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:818526```.

Tried to resinstall completely (with Revo to be sure), but the issue is still there. It happened right after uninstalling the MS C++ Redistribuables that were signaled as outdated and installed alongside the latest versions.

So I'm wondering if this is occuring only when no new updates are actualy available. Only on app updates, no issue with MS Store and WUpdate panels.

**Comment by sauceSojaaa** [comment]
Okay, did some tests.
1. I installed an outdated version of Notepad++, then check for updates: it works again.
2. I update it through UpdateHub, the update is done.
3. I search for updates again, and then the error occurs again. Exact same code as above.

So I confirm that the issue is only occuring when no available
![image](https://github.com/KK-Designs/UpdateHub/assets/119171027/7ad164c3-2058-4655-8927-52f3e77745a6)
 updates are detected. If it can help.

**Comment by KK-Designs** [comment]
Sorry for the late release, can you update to [v2.3.1](https://github.com/NexovaDev/UpdateHub/releases/tag/v2.3.1) and try again?
