### ISSUE TITLE
Getting the error ```Error: Timeout reached```

### ISSUE THREAD

**Issue by Nick-Payne** [NexovaDev/UpdateHub#365]
Getting the error ```Error: Timeout reached
    at C:\Users\nickj\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:818526```.

**Comment by Nick-Payne** [comment]
Tried twice with same error each time. app.log attached.
[app.log](https://github.com/KK-Designs/UpdateHub/files/13194102/app.log)

**Comment by Nick-Payne** [comment]
The timeout error appears to be related to UndateHub not finding any apps that need updating. After several days of getting timeout error on checking for updates, this morning the check for updates found an update for Dropbox and didn't timeout. After installing the Dropbox update, I ran another "Check for updates", and the timeout error returned.

**Comment by KK-Designs** [comment]
Sorry for the late release, can you update to [v2.3.1](https://github.com/NexovaDev/UpdateHub/releases/tag/v2.3.1) and try again?
