### ISSUE TITLE
Light mode switch is misleading

### ISSUE THREAD

**Issue by SilverGreen93** [NexovaDev/UpdateHub#375]
When activating the Dark mode switch, it changes its name to Light mode, but the switch is also switched to the right, implying that the Light mode is now turned on, when actually the Dark mode is on.

Either remove the swith entirely, or keep the name as Dark mode, otherwise this is very misleading and confuses people.

**Comment by KK-Designs** [comment]
Fixed in [v2.3.0](https://github.com/NexovaDev/UpdateHub/releases/tag/v2.3.0) 👍
