### ISSUE TITLE
Update button not always in the same place

### ISSUE THREAD

**Issue by thany** [NexovaDev/UpdateHub#398]
It's misaligned from item to item:

![image](https://github.com/NexovaDev/UpdateHub/assets/152227/00cabe2a-b36a-4b17-82e6-a71fe5768643)

**Comment by KK-Designs** [comment]
The icon seems to be preventing the update button from being on the correct side, I can fix this with some CSS tweaks, expect a fix for this soon.

**Comment by KK-Designs** [comment]
Fixed in v2.3.1 👍
