### ISSUE TITLE
This feature requires administrator mode.

### ISSUE THREAD

**Issue by nichu42** [NexovaDev/UpdateHub#431]
Getting a "This feature requires administrator mode." warning when trying to update MS Store apps or Windows, even though I have started UH in admin mode. This is new since updating to v2.3.0 and hasn't happened before.

**Comment by umbellipher** [comment]
Same for me. Whatever method I try to start it in admin mode on W11 Home 22H2 latest version, it pops up this error when I try to update Store apps. New issue, as said above, with 2.3.0.

**Comment by gurayAras** [comment]
Same here! 

I have windows 10 22H2 and UH is updated last version. I got an warning even I started to app as administrator.

**Comment by KK-Designs** [comment]
We have found out why the issue is occurring and are working on a fix. A temporary workaround would be to force close the app by pressing the shift key and then clicking the X icon in the windows title bar or by right-clicking the icon in the system tray and clicking "Close" and then relaunching the app as administrator.

**Comment by mkvGuy** [comment]
It does the same if if launched in admin

**Comment by nichu42** [comment]
The workaround doesn't help. I do not have UH in autostart, so I'm always launching it manually. And always in admin mode. The message still appears.

**Comment by Micdu70** [comment]
> The workaround doesn't help. I do not have UH in autostart, so I'm always launching it manually. And always in admin mode. The message still appears.

Me too, the last app update is broken...

**Comment by gigi2006** [comment]
same here and the workaround dont work

**Comment by Girofox** [comment]
Same isse, according to Task Manager the processes are definitely elevated as admin:

![image](https://github.com/NexovaDev/UpdateHub/assets/43116061/233dd754-d48a-4b68-a6c1-b0b20fdc6811)

**Comment by tulving** [comment]
Hi, same issue here after last update, and workaround doesn't work for me.

Thanks

App version: 2.3.0
WinGet version: 1.6.2771
OS version: 22621.2506
Node version: 18.17.1
Electron version: 27.0.0
Chrome version: 118.0.5993.54
Device ID: 48248e49-100f-48eb-8c6b-e4ddfc3436b2

**Comment by Girofox** [comment]
Did UpdateHub v2.2.3 had the same issue or just latest version?

**Comment by Micdu70** [comment]
> Did UpdateHub v2.2.3 had the same issue or just latest version?

No issue, this version is working well.

**Comment by sk666** [comment]
same issue here, workaround fix does not work for me. v 2.2.3 was fine, bug is after the 2.3.0 version.

**Comment by KK-Designs** [comment]
Working on the fix for this, will notify once I fix this

**Comment by nichu42** [comment]
Yes, it's working again. Thank you, @KK-Designs!
