### ISSUE TITLE
Administrator Mode

### ISSUE THREAD

**Issue by jakelute** [NexovaDev/UpdateHub#524]
### Debug Info:
```
App version: 2.3.0
WinGet version: 1.6.2771
OS version: 22631.2506
Node version: 18.17.1
Electron version: 27.0.0
Chrome version: 118.0.5993.54
Device ID: 22ff686e-ae6e-4709-a6bb-41b44212f64e
```

**Comment by nichu42** [comment]
Duplicate of https://github.com/NexovaDev/UpdateHub/issues/431

**Comment by KK-Designs** [comment]
Sorry for the late release, can you update to [v2.3.1](https://github.com/NexovaDev/UpdateHub/releases/tag/v2.3.1) and try again?

**Comment by jakelute** [comment]
Worked perfectly. Thank you very much.
