### ISSUE TITLE
[BUG] Apps: Shows update available for "UpdateHub" version 2.3.1 (but have version UpdateHub 2.3.1 installed)

### ISSUE THREAD

**Issue by nhwCoder** [NexovaDev/UpdateHub#735]
[Apps] Shows update available for "UpdateHub" version 2.3.1
BUT: Have version UpdateHub 2.3.1 installed

* Restarted several time and clicked for Apps on button "Check for updates".
  * Same update-available problem still displayed.

* Re-Intalled UpdateHub via download with version 2.3.1
  * Same update-available problem still displayed.

Thanks for any solution

**Comment by OsnaStonie** [comment]
Copy that completely (including reinstall).

**Comment by nhwCoder** [comment]
* There is a Update button!
* If I click on "Update" button I get the following error message (see attached [images)

![Image 009](https://github.com/NexovaDev/UpdateHub/assets/125078667/d35f62c1-d6ea-46af-bd3f-148b83b7be49)
![Image 010](https://github.com/NexovaDev/UpdateHub/assets/125078667/e4242146-fc78-43f9-8b04-0fd5d3d55b89)
![Image 011](https://github.com/NexovaDev/UpdateHub/assets/125078667/4ca70e26-59d5-40b7-ae0f-0928fd3f9abf)

**Comment by nhwCoder** [comment]
BTW: Maybe that's a hidden joke, that an update app can't update itself correctly...

**Comment by OsnaStonie** [comment]
> * There is a Update button!
> 
>     * If I click on "Update" button I get the following error message (see attached [images)

Yes, same for me here ... what I meant was that there is no "Update available Button in the left sidebar as described here: https://github.com/NexovaDev/UpdateHub/releases/tag/v2.3.1. So the App itself seems to know it is up to date but is seemingly also watching itself from a third party perspective where it is not aware of the installed version ...

**Comment by nhwCoder** [comment]
Can anyone from Nexova confirm/deny that this is a bug?

**Comment by KK-Designs** [comment]
Yes, this is a bug. I am Fixing this right now, it's because someone added UpdateHub to the winget repository, which is how UpdateHub detects updates. UpdateHub cannot update itself via winget, that's why it uses its own auto-updater (the sidebar one). It detects 2.3.0 because there appears to be two UpdateHub keys in the registry mapped to the same app, which shouldn't happen. I'll release 2.3.2 which should fix this soon, all that's left is to test it.

**Comment by nhwCoder** [comment]
Installed 2.3.2.
Seems to be fixed now.

**Comment by slord399** [comment]
seems fixed for me too.

**Comment by OsnaStonie** [comment]
> Yes, this is a bug. I am Fixing this right now, (...)
Yes, works like a charm, thanks a lot for your effort!
